// eslint-disable-next-line import/prefer-default-export
export enum FailureCode {
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  SERVER_ERROR = 'SERVER_ERROR',
  EXPIRED = 'EXPIRED',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  CAPTCHA_FAILED = 'CAPTCHA_FAILED',
  INCOMPLETE = 'INCOMPLETE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
